#!/usr/bin/env bash

# This file is to be sourced

if [[ "$TERM" != "" ]]; then
  # Disable ^S and ^Q
  stty -ixon
fi

df__ini_tput() {
  if [[ "$TERM" != "" ]]; then
    tput "$@"
  fi
}
export -f df__ini_tput

# source chunks
for bashrc_chunk in $(/bin/ls -A ~/.bashrc.d/*.*.bashrc); do
  . "$bashrc_chunk"
done

# source local configs
if [[ ! -z $DF_LOCAL_CONFIGS ]]; then
  . $DF_LOCAL_CONFIGS/local.bashrc
fi

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

KEEP_MR01_CLI_AC_BASH_SETUP_PATH=/home/df/.cache/keep-mr01-cli/autocomplete/bash_setup && test -f $KEEP_MR01_CLI_AC_BASH_SETUP_PATH && source $KEEP_MR01_CLI_AC_BASH_SETUP_PATH; # keep-mr01-cli autocomplete setup

VOLTA_HOME="$HOME/.volta"
PATH="$PATH:$VOLTA_HOME/bin"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [[ "$OSTYPE" = "darwin"* && $(whoami) = "danylofedorov" ]]; then
  . $HOME/.env-setup.sh
fi
